package dev.sabri.securityjwt.scopes.notifications;

public enum NotificationType {
    ORDER_PLACED, ORDER_RECEIVED, ORDER_OUT_FOR_DELIVERY, NEW_APPOINTMENT_REQUEST, APPOINTMENT_TIME_CHANGE_REQUESTED, APPOINTMENT_REQUEST_ACCEPTED, APPOINTMENT_REJECTED, APPOINTMENT_REQUEST_DECLINED, APPOINTMENT_CANCELLED
    , ORDER_ACCEPTED, ORDER_DECLINED
    // aro onek type add hobe pore
}
